standardisations:
#FOR TESTING 5022 IS IN SET
  categories: 
    huisletters: [ "5233", "5238", "5271", "5290", "5291", "5292", "5293", "5294"]
    Postcode_nederland: ["5022", "5035", "5041", "5054"]
  specific: 
    #CAN ALSO BE OTHER WAY AROUND, VARIABLES WHICH HAVE DEFINED THE FUNCTION ASSIGNED TO THEM 
    #FOR TESTING 2724 IS IN SET
    zeroPrefixer: ["15", "625", "2724","3380","4038","4373","4458","4622","4624","4628","4642","4773","5050","5162","5345","5349"]
  generic:
    removeDecimals: ["number"]
  categoryBased:  
    capitalize: ["huisletters", "Postcode_nederland"]




